media: static
content: 
  - name: posts
    label: Posts
    type: collection
    path: content/no/docs
    fields:
    - { name: title, label: Title, type: string}
    - { name: layout, type: string, hidden: true, default: post }
    - { name: date, label: Date, type: date}
    - { name: description, label: Description, type: string}
    - { name: body, label: Body, type: rich-text}